# [START functions_ci_cd_cloud_build]
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    dir: 'functions'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'functions',
        'deploy',
        'cicd',
        '--trigger-http',
        '--runtime',
        'nodejs14',
        '--entry-point',
        'cicd',
      ]
    dir: 'functions'
# [END functions_ci_cd_cloud_build]
